using System.Web;

namespace PMIS.Common
{
    //This util class is used to provide some generic functionality for AJAX calls.
    //It forms the responses for the calls generated by the Ajax.js JS logic.
    public static class AJAXTools
    {
        //Possible statuses of a particula ajax call
        public const string OK = "OK";
        public const string ERROR = "ERROR";
        public const string NOTLOGGEDIN = "NOTLOGGEDIN";
        public const string NOACCESS = "NOACCESS";

        //Escape some special charactes (e.g. &) before putting the content into the XML.
        public static string EncodeForXML(string value)
        {
            return HttpContext.Current.Server.HtmlEncode(value);
        }

        //Return "access denied" when the particular user do not have an access to a prticular page and/or function
        public static void AccessDenied(HttpResponse _httpresponse)
        {
            AJAX a = new AJAX("", NOACCESS, _httpresponse);
            a.Write();
            _httpresponse.End();
        }

        //Return "not logged in" when the Forsm Authentication session has been expired
        public static void NotLoggedIn(HttpResponse _httpresponse)
        {
            AJAX a = new AJAX("", NOTLOGGEDIN, _httpresponse);
            a.Write();
            _httpresponse.End();
        }
    }

    //This is the AJAX response class
    public class AJAX
    {
        private string response = "";
        private HttpResponse httpresponse = null;
        private string status = AJAXTools.OK;

        public AJAX(string _response, HttpResponse _httpresponse)
        {
            response = _response;
            httpresponse = _httpresponse;
        }

        public AJAX(string _response, string _status, HttpResponse _httpresponse)
            : this(_response, _httpresponse)
        {
            status = _status;

            if (_status == AJAXTools.NOACCESS && _response == "")
                response = "Достъпът ви е отказан!";

            if (_status == AJAXTools.NOTLOGGEDIN && _response == "")
                response = "Сесията ви е изтекла!";

            if (_status == AJAXTools.ERROR && _response == "")
                response = "Възникнала е грешка на сървъра!";
        }

        //We generate the XML document only here for better reuse
        public void Write()
        {
            string ret = @"<?xml version=""1.0"" encoding=""UTF-8""?>
                           <ajax>
                              <status>" + status + @"</status>
                              <response>" + response + @"</response>
                           </ajax>";

            httpresponse.Clear();
            httpresponse.ContentType = "text/xml";
            httpresponse.Write(ret);
        }
    }
}
